### ISSUE TITLE
Peer-to-Peer-Code-Review

### ISSUE THREAD

**Issue by kinginthenorthcodez** [franciscoPonceDev/Portfolio#13]
Isaac:   Francis your codebase is clean and precise apart that i noticed you have multiple js files in the project, I would suggest having the code in a single js file that way you could only make a single call to script to implement your functionality.
everything else is good. 👍🏽

**Comment by franciscoPonceDev** [comment]
> 



> Isaac: Francis your codebase is clean and precise apart that i noticed you have multiple js files in the project, I would suggest having the code in a single js file that way you could only make a single call to script to implement your functionality. everything else is good. 👍🏽

Thank you for your suggestion Isaac!

**Comment by franciscoPonceDev** [comment]
Thank you for your suggestion Isaac!
